name: geotagged_tweets
channels:
- conda-forge
dependencies:
- appnope=0.1.4
- asttokens=2.4.1
- brotli=1.1.0
- brotli-bin=1.1.0
- bzip2=1.0.8
- c-ares=1.33.0
- ca-certificates=2024.7.4
- cartopy=0.23.0
- certifi=2024.7.4
- comm=0.2.2
- contourpy=1.2.1
- cycler=0.12.1
- debugpy=1.8.5
- decorator=5.1.1
- et_xmlfile=1.1.0
- exceptiongroup=1.2.2
- executing=2.0.1
- fonttools=4.53.1
- freetype=2.12.1
- geographiclib=2.0
- geopy=2.4.1
- geos=3.12.2
- importlib-metadata=8.3.0
- importlib_metadata=8.3.0
- ipykernel=6.29.5
- ipython=8.26.0
- jedi=0.19.1
- jupyter_client=8.6.2
- jupyter_core=5.7.2
- kiwisolver=1.4.5
- krb5=1.21.3
- lcms2=2.16
- lerc=4.0.0
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libcurl=8.9.1
- libcxx=18.1.8
- libdeflate=1.21
- libedit=3.1.20191231
- libev=4.33
- libexpat=2.6.2
- libffi=3.4.2
- libgfortran=5.0.0
- libgfortran5=13.2.0
- libjpeg-turbo=3.0.0
- liblapack=3.9.0
- libnghttp2=1.58.0
- libopenblas=0.3.27
- libpng=1.6.43
- libsodium=1.0.18
- libsqlite=3.46.0
- libssh2=1.11.0
- libtiff=4.6.0
- libwebp-base=1.4.0
- libxcb=1.16
- libzlib=1.3.1
- llvm-openmp=18.1.8
- matplotlib=3.9.2
- matplotlib-base=3.9.2
- matplotlib-inline=0.1.7
- munkres=1.1.4
- ncurses=6.5
- nest-asyncio=1.6.0
- numpy=2.1.0
- openjpeg=2.5.2
- openpyxl=3.1.5
- openssl=3.3.1
- packaging=24.1
- pandas=2.2.2
- parso=0.8.4
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=10.4.0
- pip=24.2
- platformdirs=4.2.2
- proj=9.4.1
- prompt-toolkit=3.0.47
- psutil=6.0.0
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pure_eval=0.2.3
- pygments=2.18.0
- pyparsing=3.1.2
- pyproj=3.6.1
- pyshp=2.3.1
- python=3.12.5
- python-dateutil=2.9.0
- python-tzdata=2024.1
- python_abi=3.12
- pytz=2024.1
- pyzmq=26.1.1
- qhull=2020.2
- readline=8.2
- scipy=1.14.0
- setuptools=72.1.0
- shapely=2.0.6
- six=1.16.0
- sqlite=3.46.0
- stack_data=0.6.2
- tk=8.6.13
- tornado=6.4.1
- traitlets=5.14.3
- typing_extensions=4.12.2
- tzdata=2024a
- wcwidth=0.2.13
- wheel=0.44.0
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xz=5.2.6
- zeromq=4.3.5
- zipp=3.20.0
- zstd=1.5.6

